apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.project }}-backend-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: {{ .Values.project }}-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: {{ .Values.project }}/db
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.project }}/db
        property: password
    - secretKey: APP_JWT_SECRET
      remoteRef:
        key: {{ .Values.project }}/jwt
    - secretKey: APP_RAZORPAY_KEY_ID
      remoteRef:
        key: {{ .Values.project }}/razorpay
        property: key_id
    - secretKey: APP_RAZORPAY_KEY_SECRET
      remoteRef:
        key: {{ .Values.project }}/razorpay
        property: key_secret
