apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-sonarqube-postgres
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
