apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: sonarqube-postgres
  ports:
    - port: 5432
      targetPort: 5432
