apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project }}-sonarqube-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.project }}-sonarqube-postgres
  ports:
    - port: 5432
      targetPort: 5432
