apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickmart-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohitjangale8/pinakaone-gitops.git
    targetRevision: dev
    path: charts/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: quickmart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
