apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.project }}-mysql-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: {{ .Values.project }}-mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.project }}/db
        property: root_password
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.project }}/db
        property: database
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.project }}/db
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.project }}/db
        property: password
    - secretKey: MYSQL_ADMIN_USER
      remoteRef:
        key: {{ .Values.project }}/db
        property: admin_username
    - secretKey: MYSQL_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.project }}/db
        property: admin_password
    - secretKey: MYSQL_LOCAL_USER
      remoteRef:
        key: {{ .Values.project }}/db
        property: local_username
    - secretKey: MYSQL_LOCAL_PASSWORD
      remoteRef:
        key: {{ .Values.project }}/db
        property: local_password
